Add Loading Spinners to Components in `home.py`
e-mission/op-admin-dashboard pull request #143
Opened 2024-10-11 18:48 UTC by TeachMeTW

## Summary

This pull request introduces loading spinners for the components in `home.py` to provide better user feedback during data fetching and updates. The spinners will appear when the callback functions are being executed, improving the overall user experience.

## Changes

- Added `dcc.Loading` components to:
  - User, Active Users, and Trips cards.
  - Sign-up and Trips trend graphs.
  
- Ensured that each `dcc.Loading` component wraps around the respective element to display a loading spinner when data is being fetched or processed.

- Adjusted callbacks to ensure they trigger the spinners when necessary, providing real-time loading feedback.

## Impact

- **Improved User Experience**: The addition of spinners gives users visual feedback during operations, making the app feel more responsive and user-friendly.

## Downside

- **Double Loading Spinners**: There is now two loading spinners (component and page itself)

Resolves #134

2024-10-11 19:09 UTC, TeachMeTW commented
CURRENTLY WIP:
Skeleton Loading/Differentiation between component and page

2024-10-15 21:18 UTC, TeachMeTW commented
Accidentally commited to wrong branch; tried to fix

2024-10-15 21:46 UTC, TeachMeTW commented
@JGreenlee @shankari 

I've implemented skeleton loading for the app, but I’m unsure about one detail. Right now, some components load faster than others, creating a staggered loading experience. I’m considering whether it would be better to have all components wait for the slowest one to finish loading before displaying everything together.

Visually, it seems more cohesive to have everything appear at once, but I’m concerned this might negatively impact perceived performance since faster components are delayed.

Would love to hear your thoughts on which approach is better from a UX/design perspective:

Staggered loading (as it is now)
Unified loading (wait for all components to finish before displaying)


(the video is not up to date but skeleton is implemented)

2024-10-18 18:24 UTC, JGreenlee requested changes

2024-10-18 18:24 UTC, JGreenlee commented on app_sidebar_collapsible.py
> +    app.run_server(debug=envDebug, host='0.0.0.0', port=envPort)
whitespace change

2024-10-18 18:24 UTC, JGreenlee commented on pages/home.py
> +from dash import dcc, html, Input, Output, callback, register_page, no_update
It's not clear to me what `no_update` does or why it's added. Can you add a comment in the code with an explanation (or a link to Dash documentation that explains it)?

2024-10-18 18:24 UTC, JGreenlee commented on pages/home.py
> +def update_all_components(store_uuids, store_trips, start_date, end_date, pathname, _):
I am seeing that we used to have multiple, smaller callbacks for each card. Now we have one big callback that handles everything– which is worse from a code tidiness standpoint.
Can you explain the rationale behind this?

2024-10-21 20:42 UTC, closed without merging