Removed extraneous columns and updated data.mode to a string.
e-mission/op-admin-dashboard pull request #74
Opened 2023-10-03 17:59 UTC by achasmita

2023-10-03 18:00 UTC, achasmita commented
I have excluded following columns:
``` bash
EXCLUDED_TRAJECTORIES_COLS = [
    'data.loc.type',
    'data.loc.coordinates',
    'data.local_dt.year',
    'data.local_dt.month',
    'data.local_dt.day',
    'data.local_dt.hour',
    'data.local_dt.minute',
    'data.local_dt.second',
    'data.local_dt.weekday',
    'data.local_dt.timezone',
    'data.local_dt_year',
    'data.local_dt_month',
    'data.local_dt_day',
    'data.local_dt_hour',
    'data.local_dt_minute',
    'data.local_dt_second',
    'data.local_dt_weekday',
    'data.local_dt_timezone',
]
```

2023-10-03 18:04 UTC, achasmita commented
Here is the screenshot for columns in recent table:
<img width="1637" alt="Screen Shot 2023-10-03 at 11 01 30 AM" src="https://github.com/e-mission/op-admin-dashboard/assets/79387860/80330872-1867-405c-a1cb-9746d58cc91e">
<img width="1645" alt="Screen Shot 2023-10-03 at 11 02 32 AM" src="https://github.com/e-mission/op-admin-dashboard/assets/79387860/5aab7cd2-b9d7-4cab-a801-a4b050553677">
<img width="1680" alt="Screen Shot 2023-10-03 at 11 02 57 AM" src="https://github.com/e-mission/op-admin-dashboard/assets/79387860/c3fa8038-7640-4c6b-a77e-377cdb7111a9">

2023-10-05 04:17 UTC, shankari requested changes

2023-10-05 04:17 UTC, shankari commented on utils/db_utils.py
> +    df['data.mode'] = df['data.mode'].apply(lambda x: ecwm.PredictedModeTypes(x).name if x in set(enum.value for enum in ecwm.PredictedModeTypes) else 'UNKNOWN')
`mode` is a `MotionTypes` not a `PredictedModeTypes`
Please make sure to understand and double-check the OpenPATH data model
https://github.com/e-mission/e-mission-server/blob/bc78230d3196ca10249b6e95898f63fddf924f6f/emission/core/wrapper/recreatedlocation.py#L20

2023-10-06 02:56 UTC, shankari commented
I can't modify this repo, so merging and then fixing immediately

2023-10-06 02:56 UTC, shankari approved these changes

2023-10-06 02:58 UTC, merged