replacing datetime with arrow
e-mission/op-admin-dashboard pull request #82
Opened 2023-10-19 06:19 UTC by achasmita

fixed issue #73

2023-10-19 06:21 UTC, achasmita commented
Data is same before and after changes for trajectory and trip table:
![Screen Shot 2023-10-18 at 11 06 22 PM](https://github.com/e-mission/op-admin-dashboard/assets/79387860/4410ffee-1a38-495d-aede-29f72502dedd)
![Screen Shot 2023-10-18 at 11 06 39 PM](https://github.com/e-mission/op-admin-dashboard/assets/79387860/8fd6214f-4b16-4509-bcce-dea4e6190626)

2023-10-20 16:21 UTC, achasmita commented
Since there is no data in recent 7 days, the table appears blank
![Screen Shot 2023-10-20 at 9 13 42 AM](https://github.com/e-mission/op-admin-dashboard/assets/79387860/f7407ebe-fcc5-4683-93ef-199e9df117fe)
We can select date from filter and load data accordingly:
![Screen Shot 2023-10-20 at 9 15 12 AM](https://github.com/e-mission/op-admin-dashboard/assets/79387860/ec06e31d-fe11-470a-a523-7378551da7d4)

2023-10-21 17:05 UTC, shankari requested changes
This has the hallmarks of a hastily slapped together set of changes.
- What is the rationale for some of some of the changes?
- Why are we filtering the trajectory table when working on #73? Is this also a fix for #51?
   - In which case, why are we filtering only the trajectory table?
- Where is the testing done?

Please make sure that PRs that are submitted are clean and actually ready for review.

2023-10-22 17:42 UTC, achasmita commented on utils/db_utils.py
> +                df[col] = df[col].apply(str)
I have reverted this change as  this change is already included in another commit.

2023-10-23 22:55 UTC, closed without merging