changed demographic table to display multiple survey in subtabs
e-mission/op-admin-dashboard pull request #89
Opened 2023-11-06 04:20 UTC by achasmita

2023-11-06 04:25 UTC, achasmita commented
table with single survey:
![Screen Shot 2023-11-05 at 2 55 52 PM](https://github.com/e-mission/op-admin-dashboard/assets/79387860/6d714dea-be2b-4e3e-b88e-8101b2687aff)

table with multiple surveys
![Screen Shot 2023-11-05 at 7 53 49 PM](https://github.com/e-mission/op-admin-dashboard/assets/79387860/7aa2afc5-25f0-4bbb-8330-670ae217d304)
![Screen Shot 2023-11-05 at 7 54 06 PM](https://github.com/e-mission/op-admin-dashboard/assets/79387860/2301ba4f-4957-4d9f-abcc-da2e276cb39b)
![Screen Shot 2023-11-05 at 7 54 16 PM](https://github.com/e-mission/op-admin-dashboard/assets/79387860/602f79c2-c5b2-4fb1-97fa-2927217fe6d7)
![Screen Shot 2023-11-05 at 7 54 25 PM](https://github.com/e-mission/op-admin-dashboard/assets/79387860/be7bcdb2-3ba4-43e4-9ef9-0c36b637ee8a)

2023-11-09 22:24 UTC, shankari requested changes
Almost there, only need a few comments/cleanups

2023-11-09 22:24 UTC, shankari commented on pages/data.py
> +        df = clean_location_data(df)
why are we setting the demographic dataframe to a location dataframe?

2023-11-09 22:24 UTC, shankari commented on utils/db_utils.py
>      ts = esta.TimeSeries.get_aggregate_time_series()
you should add a comment here highlighting the different return type here since it is not the same as the other dataframes.

2023-11-12 10:15 UTC, achasmita commented on pages/data.py
> +            has_perm = perm_utils.has_permission('data_demographics')
Yes, it there is only one survey it will instantly check and create table else it will check once subtab is created.

2023-11-16 02:13 UTC, shankari requested changes

2023-11-16 02:13 UTC, shankari commented on pages/data.py
> +            has_perm = perm_utils.has_permission('data_demographics')
Right, but I don't see the need for this distinction
why can you not just check this outside the `if`?
Also the `has_perm` set in here is used in

```
 95     df = pd.DataFrame(data)
 96     if df.empty or not has_perm:
 97         return None
 98
```

so it is not clear how setting it in the callback for the demographic table subtabs helps in any way

Have you actually tried testing this? If you set the `data_demographics` permission to false, does it actually get hidden?

2023-11-16 19:14 UTC, shankari commented on pages/data.py
> +            has_perm = perm_utils.has_permission('data_demographics')
> Yes, it doensnot matter, it functions same whether we keep it in or out of if.

I don't understand/believe this. the check for `has_perm` is in `render_content`.
Setting a variable in `populate_datatable` should not affect the check - `has_perm` is not a global variable.
If you claim that it does - can you explain why?

The way that you are testing is incorrect wrt end to end testing - you need actually use a config that has the field set.

2023-11-16 21:04 UTC, achasmita commented on pages/data.py
> +            has_perm = perm_utils.has_permission('data_demographics')
<details>

<summary>This function is  in permission.py:  </summary>

>Added this to check if has_perm is working and it gives same above result.
         ```permissions['data_demographics'] = [False]```

```  bash
STUDY_CONFIG = os.getenv('STUDY_CONFIG')
PATH = os.getenv('CONFIG_PATH')
CONFIG_URL = PATH + STUDY_CONFIG + ".nrel-op.json"
response = requests.get(CONFIG_URL)
config = json.loads(response.text)
surveyinfo = config.get("survey_info",
    {
      "surveys": {
        "UserProfileSurvey": {
          "formPath": "json/demo-survey-v2.json",
          "version": 1,
          "compatibleWith": 1,
          "dataKey": "manual/demographic_survey",
          "labelTemplate": {
            "en": "Answered",
            "es": "Contestada"
          }
        }
      },
      "trip-labels": "MULTILABEL"
    })
permissions = config.get("admin_dashboard", {})
permissions['data_demographics'] = [False]

def has_permission(perm):
    return False if permissions.get(perm) is False else True
```

</details>

2023-11-23 06:13 UTC, shankari requested changes

2023-11-23 06:13 UTC, shankari commented on pages/data.py
> +            has_perm = perm_utils.has_permission('data_demographics')
@achasmita as we discussed, I don't see how setting this here affects anything in the main tab. you should remove this line. you might need to move the `has_perm` check in `render_context` before the `if` to compensate.

2023-12-02 04:10 UTC, shankari approved these changes

2023-12-02 04:25 UTC, shankari requested changes

2023-12-02 04:25 UTC, shankari commented on pages/data.py
> +            data = next(iter(data.values()))
@achasmita I had commented on this in:
https://github.com/e-mission/op-admin-dashboard/pull/89#discussion_r1388628743

you removed it in 
https://github.com/e-mission/op-admin-dashboard/pull/89/commits/53dafd6af1a2f4d36f0cabd49b3418fc24973539

but now that I check the code, this is still here.

Please fix.

2023-12-02 04:25 UTC, shankari commented on utils/db_utils.py
> +        survey_key = next(iter(entry['data']['jsonDocResponse']))
Ditto

2023-12-03 04:40 UTC, shankari commented
@achasmita please fill in "testing done"

2023-12-03 20:16 UTC, shankari commented
Going to merge this now.
Note that I am squash-merging this, so please handle it properly while merging changes from upstream.

2023-12-03 20:17 UTC, merged